# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatmates', '0003_auto_20160726_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='spent_amount',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='spent_date',
        ),
    ]
