# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 22:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flatmates', '0006_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expense',
            field=models.CharField(default='Groceries', max_length=100),
        ),
        migrations.AddField(
            model_name='expenses',
            name='spent_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expenses',
            name='spent_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 22, 34, 43, 772110, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(default='NULL', max_length=300),
        ),
    ]
