# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatmates', '0010_auto_20160726_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(default='self Explainable!!', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joining_date',
            field=models.DateTimeField(),
        ),
    ]
